### ISSUE TITLE
Problem with custom prompt 

### ISSUE THREAD

**Issue by SamDc73** [coloradocolby/thokr#12]
## Description
I have a test file with around 50 words that have this structure : (word in each line with no space at the end)
```
dependencies
visualization
description
parse
duplicates
possible
nootropics
scissors
```
now when i run `thokr -p "$(cat Notes/typing/words)" ` the app show like this : ( wiht no spaces between words)
```
dependenciesvisualizationdescriptionparseduplicatespossible
nootropicsscissors
```

## To Reproduce

I tried to add space after each word in the text file and it worded almost : the problem i had is that i need to type <space> twice for each <space> 

## Expected behavior

To show the words with spaces 

## Environment
- OS: Linux Fedora 36 KDE 
- Terminal Emulator: kitty 
- Font: JetBrainsMono Nerd Font
- Thokr Version:  0.3.0

**Comment by coloradocolby** [comment]
I don't want thokr to make any assumptions on how to process the input it's provided. In this case you could run something like `thokr -p "$(echo $(cat input.txt))"` to achieve the desired result.
