### ISSUE TITLE
Fresh warp terminal bug

### ISSUE THREAD

**Issue by junque1r4** [coloradocolby/thokr#15]
## Description
When I start a fresh terminal and run thokr for the first time it doesn't load any graphic until I run it again

## To Reproduce
Run thokr in a fresh warp terminal.

## Expected behavior

It's expected that it shows some graphics, isn't it?

## Screenshots

first run in a fresh terminal:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/39351332/175514524-667a3b5c-bea8-4b8f-9197-190eb45895c0.png">
after retry:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/39351332/175514703-6cabe051-adc1-4582-a0df-98a39fa41ae1.png">

video:

https://user-images.githubusercontent.com/39351332/175514836-d22ee8f4-8641-4ca4-83cb-bdaa07ecdcca.mov

## Environment

- OS: macOS Monterey 12.4 (21F79)
- Terminal Emulator: warp
- Font: hack (warp default)
- Thokr Version: 0.4.0

## Additional context
I'm not an English speaker so sorry for any language mistake...

In iTerm it runs normally...

**Comment by jrnxf** [comment]
Sounds like this is more likely a warp bug than a thokr bug? I could be wrong but the fact it works on run two is fishy

**Comment by junque1r4** [comment]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/39351332/179817066-1a0a3c7f-92eb-4e02-9faf-1faf40df6c90.png">

I was trying today again and after a while the points shows at the first try!
