### ISSUE TITLE
Multi-byte codepoints cause panic

### ISSUE THREAD

**Issue by bluelhf** [coloradocolby/thokr#16]
## Description

When a multiple-byte codepoint is rendered in the prompt, `thokr` panics and dies.

## To Reproduce

Run `thokr -p "ä"`
Observe the panic.

## Expected behavior

Thokr should render the character properly, without panicking.

## Environment

- OS: Devuan GNU/Linux Ceres on amd64
- Terminal Emulator: gnome-terminal
- Font: JetBrains Mono Nerd Font
- Crate version: 0.3.0

## Additional context
I suspect the source of the panic can be found on [line 64 in thok.rs](https://github.com/thatvegandev/thokr/blob/9453468032cae753570b660146103abd55609df2/src/thok.rs#L64).
https://github.com/thatvegandev/thokr/blob/9453468032cae753570b660146103abd55609df2/src/thok.rs#L64

**Comment by bluelhf** [comment]
Ah, I see you actually have mentioned this in the README. What kinds of rendering issues did characters with diacritics previously cause?

**Comment by jrnxf** [comment]
It's been a while but I seem to remember the error being that you simply would be blocked entirely unless you were able to type the character in one keypress. I also remember having issues regarding the actual space a special character (eg one with diacritics) takes up, causing some issues with strings. I don't have the bandwidth to work on this right now, so I'm going to close the ticket, but this is personally the issue I'd like to see resolved the most if anyone has any ideas!
